dubbo:
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
#    protocol: nacos
#    address: 127.0.0.1:8848
    id: registry-1
  protocol:
    port: 20888
    name: dubbo
    id: dubbo
    status: server
  application:
    name: ilss-provider
    id: ilss-provider
  scan:
    basePackages: com.lls.provider.service
  provider:
    version: 1.0
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbit1
    password: rabbit1
    virtual-host: rabbit1Host
    #确认消息已发送到交换机
    publisher-confirms: true
    #确认消息已发送到队列
    publisher-returns: true

rabbitmq:
  exchange:
   topic-exchange: topicExchange
