dubbo:
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
#    protocol: nacos
#    address: 127.0.0.1:8848
    id: registry-1
  protocol:
    port: 20888
    name: dubbo
    id: dubbo
    status: server
  application:
    name: ilss-provider
    id: ilss-provider
  scan:
    basePackages: com.lls.provider.service
  provider:
    version: 1.0
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbit1
    password: rabbit1
    virtual-host: rabbit1Host
    #确认消息已发送到交换机
    publisher-confirms: true
    #确认消息已发送到队列
    publisher-returns: true
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
  # kafka 配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/temp?serverTimezone=UTC
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: MYSQL
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

rabbitmq:
  exchange:
   topic-exchange: topicExchange
