server:
  port: 5510
spring:
  profiles:
    active: dev
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: rabbit1
    password: rabbit1
    virtual-host: rabbit1Host
  # kafka 配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
